### ISSUE TITLE
Ознакомился с задачей. Готов выполнить задание.

### ISSUE THREAD

**Issue by SergeyZhuck1982** [damianua/bx_quiz#5]
Ознакомился с задачей. Готов выполнить задание.
Мне было бы удобно иметь развернутый сервер где выполнять задачу, а также SSH доступ к нему.

**Comment by damianua** [comment]
Спасибо за отклик.
Что касается сервера - давайте представим, что настройка рабочего окружение для разработки проекта на Битрикс на локальной машине(выделенном сервере/среде разработки codenvy или Cloud9) также является, своего рода, индикатором компетентности разработчика )
